[2023-06-22T16:13:38.515+0200] {processor.py:157} INFO - Started process (PID=87291) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:13:38.517+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:13:38.517+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:13:38.517+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:13:38.552+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:13:38.550+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:13:38.553+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:13:39.157+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.642 seconds
[2023-06-22T16:14:10.450+0200] {processor.py:157} INFO - Started process (PID=87302) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:10.452+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:14:10.453+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:14:10.453+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:10.480+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:14:10.480+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:14:10.481+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:11.028+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.578 seconds
[2023-06-22T16:14:42.283+0200] {processor.py:157} INFO - Started process (PID=87312) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:42.285+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:14:42.285+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:14:42.285+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:42.312+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:14:42.311+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:14:42.312+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:14:42.853+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.570 seconds
[2023-06-22T16:15:14.141+0200] {processor.py:157} INFO - Started process (PID=87322) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:14.143+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:15:14.143+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:15:14.143+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:14.171+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:15:14.170+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:15:14.171+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:14.713+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.573 seconds
[2023-06-22T16:15:46.009+0200] {processor.py:157} INFO - Started process (PID=87333) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:46.011+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:15:46.011+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:15:46.011+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:46.039+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:15:46.039+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:15:46.040+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:15:46.589+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.581 seconds
[2023-06-22T16:16:17.877+0200] {processor.py:157} INFO - Started process (PID=87343) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:17.879+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:16:17.880+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:16:17.880+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:17.907+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:16:17.906+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:16:17.907+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:18.450+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.574 seconds
[2023-06-22T16:16:50.215+0200] {processor.py:157} INFO - Started process (PID=87355) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:50.217+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:16:50.217+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:16:50.217+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:50.244+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:16:50.244+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:16:50.244+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:16:50.811+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.597 seconds
[2023-06-22T16:17:22.166+0200] {processor.py:157} INFO - Started process (PID=87367) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:22.169+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:17:22.169+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:17:22.169+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:22.198+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:17:22.197+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:17:22.198+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:22.753+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.587 seconds
[2023-06-22T16:17:53.958+0200] {processor.py:157} INFO - Started process (PID=87377) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:53.960+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:17:53.961+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:17:53.961+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:53.988+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:17:53.988+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:17:53.988+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:17:54.541+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.583 seconds
[2023-06-22T16:18:25.864+0200] {processor.py:157} INFO - Started process (PID=87387) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:25.867+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:18:25.867+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:18:25.867+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:25.899+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:18:25.898+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:18:25.899+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:26.443+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.580 seconds
[2023-06-22T16:18:57.767+0200] {processor.py:157} INFO - Started process (PID=87399) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:57.769+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:18:57.769+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:18:57.769+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:57.797+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:18:57.797+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:18:57.798+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:18:58.356+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.590 seconds
[2023-06-22T16:19:29.701+0200] {processor.py:157} INFO - Started process (PID=87409) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:19:29.703+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:19:29.703+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:19:29.703+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:19:29.731+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:19:29.730+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:19:29.731+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:19:30.275+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.574 seconds
[2023-06-22T16:20:01.555+0200] {processor.py:157} INFO - Started process (PID=87420) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:01.557+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:20:01.557+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:20:01.557+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:01.584+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:20:01.584+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:20:01.584+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:02.148+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.594 seconds
[2023-06-22T16:20:33.531+0200] {processor.py:157} INFO - Started process (PID=87431) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:33.534+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:20:33.534+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:20:33.534+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:33.561+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:20:33.560+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:20:33.561+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:20:34.106+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.576 seconds
[2023-06-22T16:21:05.446+0200] {processor.py:157} INFO - Started process (PID=87442) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:05.449+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:21:05.449+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:21:05.449+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:05.476+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:21:05.475+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:21:05.476+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:06.047+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.601 seconds
[2023-06-22T16:21:37.409+0200] {processor.py:157} INFO - Started process (PID=87454) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:37.411+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:21:37.411+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:21:37.411+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:37.439+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:21:37.439+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:21:37.440+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:21:37.991+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.583 seconds
[2023-06-22T16:22:09.314+0200] {processor.py:157} INFO - Started process (PID=87467) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:09.316+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:22:09.316+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:22:09.316+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:09.343+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:22:09.342+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:22:09.343+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:09.884+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.571 seconds
[2023-06-22T16:22:41.181+0200] {processor.py:157} INFO - Started process (PID=87478) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:41.183+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:22:41.183+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:22:41.183+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:41.210+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:22:41.209+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:22:41.210+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:22:41.753+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.573 seconds
[2023-06-22T16:23:12.997+0200] {processor.py:157} INFO - Started process (PID=87488) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:12.999+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:23:12.999+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:23:12.999+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:13.027+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:23:13.026+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:23:13.027+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:13.569+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.572 seconds
[2023-06-22T16:23:44.908+0200] {processor.py:157} INFO - Started process (PID=87500) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:44.910+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:23:44.910+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:23:44.910+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:44.938+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:23:44.937+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:23:44.938+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:23:45.486+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.578 seconds
[2023-06-22T16:24:16.798+0200] {processor.py:157} INFO - Started process (PID=87511) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:16.801+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:24:16.801+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:24:16.801+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:16.828+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:24:16.827+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:24:16.828+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:17.381+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.583 seconds
[2023-06-22T16:24:48.674+0200] {processor.py:157} INFO - Started process (PID=87521) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:48.676+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:24:48.676+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:24:48.676+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:48.704+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:24:48.703+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:24:48.704+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:24:49.272+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.599 seconds
[2023-06-22T16:25:20.576+0200] {processor.py:157} INFO - Started process (PID=87531) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:20.578+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:25:20.579+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:25:20.579+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:20.605+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:25:20.605+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:25:20.605+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:21.141+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.566 seconds
[2023-06-22T16:25:52.479+0200] {processor.py:157} INFO - Started process (PID=87550) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:52.481+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:25:52.482+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:25:52.482+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:52.510+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:25:52.509+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:25:52.510+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:25:53.076+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.597 seconds
[2023-06-22T16:26:24.478+0200] {processor.py:157} INFO - Started process (PID=87560) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:24.480+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:26:24.480+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:26:24.480+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:24.509+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:26:24.508+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:26:24.509+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:25.067+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.590 seconds
[2023-06-22T16:26:56.538+0200] {processor.py:157} INFO - Started process (PID=87574) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:56.541+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:26:56.541+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:26:56.541+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:56.570+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:26:56.570+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:26:56.571+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:26:57.127+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.589 seconds
[2023-06-22T16:27:28.769+0200] {processor.py:157} INFO - Started process (PID=87590) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:27:28.772+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:27:28.773+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:27:28.773+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:27:28.802+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:27:28.801+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:27:28.802+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:27:29.391+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.622 seconds
[2023-06-22T16:28:00.602+0200] {processor.py:157} INFO - Started process (PID=87604) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:00.605+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:28:00.605+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:28:00.605+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:00.640+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:28:00.640+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:28:00.641+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:01.260+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.659 seconds
[2023-06-22T16:28:30.495+0200] {processor.py:157} INFO - Started process (PID=87622) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:30.497+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:28:30.498+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:28:30.498+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:30.531+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:28:30.531+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:28:30.532+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:28:31.169+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.675 seconds
[2023-06-22T16:29:02.478+0200] {processor.py:157} INFO - Started process (PID=87637) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:02.481+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:29:02.482+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:29:02.482+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:02.520+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:29:02.517+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:29:02.520+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:03.109+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.631 seconds
[2023-06-22T16:29:34.466+0200] {processor.py:157} INFO - Started process (PID=87647) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:34.469+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:29:34.469+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:29:34.469+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:34.497+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:29:34.496+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:29:34.497+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:29:35.058+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.592 seconds
[2023-06-22T16:30:06.450+0200] {processor.py:157} INFO - Started process (PID=87659) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:06.453+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:30:06.453+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:30:06.453+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:06.485+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:30:06.484+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:30:06.485+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:07.105+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.656 seconds
[2023-06-22T16:30:38.535+0200] {processor.py:157} INFO - Started process (PID=87670) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:38.538+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:30:38.538+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:30:38.538+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:38.565+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:30:38.564+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:30:38.565+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:30:39.106+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.571 seconds
[2023-06-22T16:31:10.358+0200] {processor.py:157} INFO - Started process (PID=87680) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:10.361+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:31:10.361+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:31:10.361+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:10.390+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:31:10.389+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:31:10.390+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:10.943+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.585 seconds
[2023-06-22T16:31:42.351+0200] {processor.py:157} INFO - Started process (PID=87693) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:42.353+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:31:42.354+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:31:42.354+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:42.387+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:31:42.386+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:31:42.387+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:31:43.030+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.679 seconds
[2023-06-22T16:32:14.961+0200] {processor.py:157} INFO - Started process (PID=87710) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:14.964+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:32:14.964+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:32:14.964+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:14.993+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:32:14.992+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:32:14.993+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:15.559+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.598 seconds
[2023-06-22T16:32:33.350+0200] {processor.py:157} INFO - Started process (PID=87719) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:33.352+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:32:33.353+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:32:33.353+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:33.388+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:32:33.388+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:32:33.389+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:32:34.052+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.703 seconds
[2023-06-22T16:33:05.791+0200] {processor.py:157} INFO - Started process (PID=87778) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:05.793+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:33:05.793+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:33:05.793+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:05.821+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:33:05.821+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:33:05.821+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:06.374+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.584 seconds
[2023-06-22T16:33:38.100+0200] {processor.py:157} INFO - Started process (PID=87788) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:38.102+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:33:38.103+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:33:38.103+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:38.131+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:33:38.131+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:33:38.131+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:33:38.689+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.589 seconds
[2023-06-22T16:34:10.550+0200] {processor.py:157} INFO - Started process (PID=87808) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:10.553+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:34:10.554+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:34:10.553+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:10.589+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:34:10.588+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:34:10.590+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:11.210+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.660 seconds
[2023-06-22T16:34:42.811+0200] {processor.py:157} INFO - Started process (PID=87818) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:42.813+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:34:42.813+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:34:42.813+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:42.842+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:34:42.841+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:34:42.842+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:34:43.416+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.606 seconds
[2023-06-22T16:35:15.033+0200] {processor.py:157} INFO - Started process (PID=87828) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:15.036+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:35:15.036+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:35:15.036+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:15.064+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:35:15.063+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:35:15.064+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:15.608+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.575 seconds
[2023-06-22T16:35:47.277+0200] {processor.py:157} INFO - Started process (PID=87839) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:47.280+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:35:47.280+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:35:47.280+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:47.316+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:35:47.315+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:35:47.317+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:35:47.894+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.618 seconds
[2023-06-22T16:36:19.135+0200] {processor.py:157} INFO - Started process (PID=87850) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:19.138+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:36:19.138+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:36:19.138+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:19.171+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:36:19.170+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:36:19.171+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:19.793+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.659 seconds
[2023-06-22T16:36:50.972+0200] {processor.py:157} INFO - Started process (PID=87862) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:50.975+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:36:50.975+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:36:50.975+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:51.011+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:36:51.011+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:36:51.012+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:36:51.638+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.666 seconds
[2023-06-22T16:37:10.306+0200] {processor.py:157} INFO - Started process (PID=87868) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:10.308+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:37:10.309+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:37:10.309+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:10.338+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:37:10.338+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:37:10.339+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:10.887+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.582 seconds
[2023-06-22T16:37:41.831+0200] {processor.py:157} INFO - Started process (PID=87925) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:41.833+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:37:41.834+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:37:41.834+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:41.861+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:37:41.861+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 3, in <module>
    from usecase_etl import perform_etl
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_etl.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-06-22T16:37:41.862+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:37:42.414+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.583 seconds
[2023-06-22T16:38:13.414+0200] {processor.py:157} INFO - Started process (PID=87955) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:13.416+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:38:13.416+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:38:13.416+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:23.574+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:38:23.573+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:38:23.574+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:24.094+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 10.681 seconds
[2023-06-22T16:38:55.494+0200] {processor.py:157} INFO - Started process (PID=87967) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:55.496+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:38:55.496+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:38:55.496+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:55.788+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:38:55.787+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:38:55.788+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:38:56.298+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.805 seconds
[2023-06-22T16:39:27.606+0200] {processor.py:157} INFO - Started process (PID=87978) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:39:27.608+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:39:27.609+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:39:27.609+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:39:27.895+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:39:27.895+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:39:27.896+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:39:28.415+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.809 seconds
[2023-06-22T16:39:59.682+0200] {processor.py:157} INFO - Started process (PID=87988) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:39:59.685+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:39:59.685+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:39:59.685+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:39:59.966+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:39:59.965+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:39:59.966+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:40:00.469+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.787 seconds
[2023-06-22T16:40:31.890+0200] {processor.py:157} INFO - Started process (PID=88000) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:40:31.892+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:40:31.893+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:40:31.892+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:40:32.222+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:40:32.221+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:40:32.223+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:40:32.793+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.903 seconds
[2023-06-22T16:41:03.806+0200] {processor.py:157} INFO - Started process (PID=88043) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:03.808+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:41:03.808+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:41:03.808+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:04.094+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:41:04.093+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:41:04.094+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:04.603+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.798 seconds
[2023-06-22T16:41:35.911+0200] {processor.py:157} INFO - Started process (PID=88055) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:35.914+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:41:35.914+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:41:35.914+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:36.206+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:41:36.205+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:41:36.206+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:41:36.714+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.803 seconds
[2023-06-22T16:42:08.062+0200] {processor.py:157} INFO - Started process (PID=88068) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:08.064+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:42:08.065+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:42:08.065+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:08.357+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:42:08.356+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:42:08.357+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:08.873+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.812 seconds
[2023-06-22T16:42:40.251+0200] {processor.py:157} INFO - Started process (PID=88078) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:40.253+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:42:40.254+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:42:40.254+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:40.536+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:42:40.535+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:42:40.536+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:42:41.040+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.789 seconds
[2023-06-22T16:43:12.388+0200] {processor.py:157} INFO - Started process (PID=88088) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:12.390+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:43:12.390+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:43:12.390+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:12.673+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:43:12.673+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:43:12.674+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:13.180+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.793 seconds
[2023-06-22T16:43:44.440+0200] {processor.py:157} INFO - Started process (PID=88098) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:44.442+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:43:44.442+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:43:44.442+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:44.731+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:43:44.730+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:43:44.731+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:43:45.252+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.813 seconds
[2023-06-22T16:44:16.535+0200] {processor.py:157} INFO - Started process (PID=88109) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:16.537+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:44:16.537+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:44:16.537+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:16.824+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:44:16.824+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:44:16.825+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:17.325+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.791 seconds
[2023-06-22T16:44:48.687+0200] {processor.py:157} INFO - Started process (PID=88119) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:48.689+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:44:48.690+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:44:48.689+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:48.976+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:44:48.975+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:44:48.976+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:44:49.497+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.811 seconds
[2023-06-22T16:45:20.783+0200] {processor.py:157} INFO - Started process (PID=88131) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:20.785+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:45:20.785+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:45:20.785+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:21.070+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:45:21.069+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:45:21.070+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:21.566+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.784 seconds
[2023-06-22T16:45:52.950+0200] {processor.py:157} INFO - Started process (PID=88141) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:52.952+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:45:52.953+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:45:52.953+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:53.313+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:45:53.312+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 4, in <module>
    from sklearn.linear_model import ElasticNet
ModuleNotFoundError: No module named 'sklearn'
[2023-06-22T16:45:53.313+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:45:53.936+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 0.986 seconds
[2023-06-22T16:46:25.669+0200] {processor.py:157} INFO - Started process (PID=88162) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:46:25.672+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:46:25.673+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:46:25.673+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:46:44.458+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:46:44.457+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-06-22T16:46:44.458+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:46:44.954+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 19.286 seconds
[2023-06-22T16:47:00.934+0200] {processor.py:157} INFO - Started process (PID=88204) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:00.936+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:47:00.936+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:47:00.936+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:01.878+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:47:01.877+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-06-22T16:47:01.878+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:02.377+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 1.444 seconds
[2023-06-22T16:47:33.752+0200] {processor.py:157} INFO - Started process (PID=88232) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:33.755+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:47:33.756+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:47:33.756+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:34.743+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:47:34.741+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 7, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2023-06-22T16:47:34.744+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:47:35.234+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 1.482 seconds
[2023-06-22T16:48:06.314+0200] {processor.py:157} INFO - Started process (PID=88285) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:06.319+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:48:06.319+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:06.319+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:07.748+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:07.747+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 4, in <module>
    from usecase_training import training
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_training.py", line 9, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-06-22T16:48:07.748+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:08.297+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 1.983 seconds
[2023-06-22T16:48:40.210+0200] {processor.py:157} INFO - Started process (PID=88334) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:40.215+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:48:40.215+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:40.215+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:44.191+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.191+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:48:44.310+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:48:44.903+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.903+0200] {manager.py:504} INFO - Created Permission View: can edit on DAG:dag_with_usecase
[2023-06-22T16:48:44.910+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.910+0200] {manager.py:504} INFO - Created Permission View: can read on DAG:dag_with_usecase
[2023-06-22T16:48:44.915+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.915+0200] {manager.py:504} INFO - Created Permission View: can delete on DAG:dag_with_usecase
[2023-06-22T16:48:44.915+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.915+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:48:44.923+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.923+0200] {dag.py:2747} INFO - Creating ORM DAG for dag_with_usecase
[2023-06-22T16:48:44.930+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:48:44.930+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:48:44.942+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 4.732 seconds
[2023-06-22T16:49:16.732+0200] {processor.py:157} INFO - Started process (PID=88359) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:16.735+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:49:16.735+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:16.735+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:18.389+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:18.388+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:49:18.497+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:18.883+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:18.883+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:49:18.894+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:18.894+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:49:19.008+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.276 seconds
[2023-06-22T16:49:50.515+0200] {processor.py:157} INFO - Started process (PID=88389) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:50.518+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:49:50.518+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:50.518+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:52.335+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:52.335+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:49:52.437+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:49:52.864+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:52.864+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:49:52.877+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:49:52.877+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:49:52.995+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.481 seconds
[2023-06-22T16:50:24.368+0200] {processor.py:157} INFO - Started process (PID=88406) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:24.370+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:50:24.371+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:24.371+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:25.925+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:25.925+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:50:26.031+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:26.389+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:26.389+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:50:26.400+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:26.400+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:50:26.504+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.137 seconds
[2023-06-22T16:50:34.251+0200] {processor.py:157} INFO - Started process (PID=88413) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:34.253+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:50:34.254+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:34.254+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:35.909+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:35.909+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:50:35.918+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:50:35.911+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 57, in <module>
    taskflow_dag = dag_func(path_data)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dag.py", line 3604, in factory
    f(**f_kwargs)
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 32, in dag_func
    run_id = training(filename, default_args['exp_name'])
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'exp_name'
[2023-06-22T16:50:35.919+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:50:36.377+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.126 seconds
[2023-06-22T16:51:07.789+0200] {processor.py:157} INFO - Started process (PID=88427) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:07.792+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:51:07.792+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:07.792+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:09.360+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:09.360+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:51:09.363+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:09.362+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 57, in <module>
    taskflow_dag = dag_func(path_data)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dag.py", line 3604, in factory
    f(**f_kwargs)
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 32, in dag_func
    run_id = training(filename, default_args['exp_name'])
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'exp_name'
[2023-06-22T16:51:09.363+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:09.797+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.008 seconds
[2023-06-22T16:51:41.797+0200] {processor.py:157} INFO - Started process (PID=88442) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:41.799+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:51:41.799+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:41.799+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:43.426+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:43.426+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:51:43.429+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:51:43.427+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 57, in <module>
    taskflow_dag = dag_func(path_data)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dag.py", line 3604, in factory
    f(**f_kwargs)
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 32, in dag_func
    run_id = training(filename, default_args['exp_name'])
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'exp_name'
[2023-06-22T16:51:43.429+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:51:43.865+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.069 seconds
[2023-06-22T16:52:15.287+0200] {processor.py:157} INFO - Started process (PID=88456) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:15.289+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:52:15.289+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:15.289+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:17.071+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:17.071+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:52:17.075+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:17.074+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 57, in <module>
    taskflow_dag = dag_func(path_data)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dag.py", line 3604, in factory
    f(**f_kwargs)
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 32, in dag_func
    run_id = training(filename, default_args['exp_name'])
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'exp_name'
[2023-06-22T16:52:17.076+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:17.544+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.257 seconds
[2023-06-22T16:52:48.784+0200] {processor.py:157} INFO - Started process (PID=88476) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:48.786+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:52:48.787+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:48.786+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:50.420+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:50.419+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:52:50.423+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:52:50.421+0200] {dagbag.py:350} ERROR - Failed to import: /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 57, in <module>
    taskflow_dag = dag_func(path_data)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/models/dag.py", line 3604, in factory
    f(**f_kwargs)
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py", line 32, in dag_func
    run_id = training(filename, default_args['exp_name'])
                                ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'exp_name'
[2023-06-22T16:52:50.423+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:52:50.862+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.079 seconds
[2023-06-22T16:53:22.156+0200] {processor.py:157} INFO - Started process (PID=88491) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:22.159+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:53:22.160+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:22.160+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:24.013+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:24.012+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:53:24.016+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:24.016+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:53:24.016+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:24.016+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:53:24.128+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:24.730+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:24.729+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:53:24.742+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:24.742+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:53:24.857+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.702 seconds
[2023-06-22T16:53:56.635+0200] {processor.py:157} INFO - Started process (PID=88561) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:56.639+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:53:56.639+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:56.639+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:58.446+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:58.446+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:53:58.449+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:58.449+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:53:58.449+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:58.449+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:53:58.561+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:53:59.030+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:59.030+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:53:59.042+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:53:59.042+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:53:59.151+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.516 seconds
[2023-06-22T16:54:10.004+0200] {processor.py:157} INFO - Started process (PID=88583) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:10.007+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:54:10.007+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:10.007+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:11.642+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:11.641+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:54:11.644+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:11.644+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:54:11.644+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:11.644+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:54:11.746+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:11.789+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:11.789+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:54:12.104+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:12.104+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:54:12.121+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.117 seconds
[2023-06-22T16:54:43.384+0200] {processor.py:157} INFO - Started process (PID=88597) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:43.386+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:54:43.387+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:43.387+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:44.896+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:44.896+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:54:44.899+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:44.898+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:54:44.899+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:44.899+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:54:45.008+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:54:45.370+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:45.370+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:54:45.380+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:54:45.380+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:54:45.484+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.100 seconds
[2023-06-22T16:55:16.628+0200] {processor.py:157} INFO - Started process (PID=88627) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:16.631+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:55:16.631+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:16.631+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:18.145+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:18.145+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:55:18.147+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:18.147+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:55:18.147+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:18.147+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:55:18.248+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:18.638+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:18.638+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:55:18.649+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:18.649+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:55:18.758+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.130 seconds
[2023-06-22T16:55:50.118+0200] {processor.py:157} INFO - Started process (PID=88668) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:50.122+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:55:50.122+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:50.122+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:52.825+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:52.825+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:55:52.828+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:52.828+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:55:52.829+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:52.829+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:55:52.939+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:55:53.334+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:53.334+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:55:53.346+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:55:53.346+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:55:53.454+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 3.336 seconds
[2023-06-22T16:56:25.661+0200] {processor.py:157} INFO - Started process (PID=88726) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:25.664+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:56:25.664+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:25.664+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:27.903+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:27.903+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:56:27.907+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:27.907+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:56:27.907+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:27.907+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:56:28.050+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:28.736+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:28.736+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:56:28.749+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:28.749+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:56:28.858+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 3.197 seconds
[2023-06-22T16:56:47.396+0200] {processor.py:157} INFO - Started process (PID=88748) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:47.398+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:56:47.399+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:47.398+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:49.179+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:49.179+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:56:49.181+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:49.181+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:56:49.182+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:49.182+0200] {taskmixin.py:211} WARNING - Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:56:49.287+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:56:49.331+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:49.331+0200] {dag.py:2726} INFO - Sync 1 DAGs
[2023-06-22T16:56:49.680+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:56:49.680+0200] {dag.py:3486} INFO - Setting next_dagrun for dag_with_usecase to 2023-06-23T00:00:00+00:00, run_after=2023-06-24T00:00:00+00:00
[2023-06-22T16:56:49.692+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.296 seconds
[2023-06-22T16:57:03.370+0200] {processor.py:157} INFO - Started process (PID=88756) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:03.373+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:57:03.373+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:57:03.373+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:05.059+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:57:05.059+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:57:05.792+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:57:05 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:57:05.794+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:57:05 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:57:05.799+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:57:05.799+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:57:05.824+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:57:05.824+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:57:05.839+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:57:05.839+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:57:05.843+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:05.907+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.537 seconds
[2023-06-22T16:57:37.533+0200] {processor.py:157} INFO - Started process (PID=88769) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:37.535+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:57:37.535+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:57:37.535+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:39.106+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:57:39.106+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:57:39.756+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:57:39 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:57:39.758+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:57:39 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:57:39.762+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:57:39.762+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:57:39.783+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:57:39.783+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:57:39.796+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:57:39.796+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:57:39.800+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:57:39.875+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.342 seconds
[2023-06-22T16:58:11.222+0200] {processor.py:157} INFO - Started process (PID=88817) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:11.226+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:58:11.226+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:11.226+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:13.005+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:13.005+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:58:13.695+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:13 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:58:13.697+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:13 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:58:13.702+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:13.702+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:13.723+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:13.723+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:13.737+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:58:13.737+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:58:13.742+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:13.816+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.595 seconds
[2023-06-22T16:58:45.103+0200] {processor.py:157} INFO - Started process (PID=88832) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:45.106+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:58:45.107+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:45.107+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:46.819+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:46.819+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:58:47.522+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:47 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:58:47.524+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:47 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:58:47.528+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:47.528+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:47.549+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:47.549+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:47.563+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:58:47.564+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:58:47.568+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:47.638+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.535 seconds
[2023-06-22T16:58:56.936+0200] {processor.py:157} INFO - Started process (PID=88839) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:56.939+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:58:56.939+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:56.939+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:58.636+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:58:58.636+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:58:59.343+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:59 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:58:59.344+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:58:59 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:58:59.348+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:59.349+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:59.370+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:58:59.370+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:58:59.387+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:58:59.387+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:58:59.392+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:58:59.435+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.498 seconds
[2023-06-22T16:59:30.385+0200] {processor.py:157} INFO - Started process (PID=88852) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:30.387+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:59:30.387+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:59:30.387+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:32.047+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:59:32.047+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:59:32.769+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:59:32 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:59:32.771+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:59:32 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:59:32.776+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:59:32.776+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:59:32.797+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:59:32.797+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:59:32.811+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:59:32.811+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:59:32.816+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:32.888+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.504 seconds
[2023-06-22T16:59:39.897+0200] {processor.py:157} INFO - Started process (PID=88859) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:39.899+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T16:59:39.899+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:59:39.899+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:41.459+0200] {logging_mixin.py:149} INFO - [2023-06-22T16:59:41.459+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T16:59:42.112+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:59:42 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T16:59:42.114+0200] {logging_mixin.py:149} WARNING - 2023/06/22 16:59:42 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T16:59:42.118+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:59:42.119+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:59:42.140+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T16:59:42.140+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T16:59:42.154+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T16:59:42.154+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T16:59:42.159+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T16:59:42.198+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.302 seconds
[2023-06-22T17:00:13.442+0200] {processor.py:157} INFO - Started process (PID=88871) to work on /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T17:00:13.445+0200] {processor.py:826} INFO - Processing file /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py for tasks to queue
[2023-06-22T17:00:13.445+0200] {logging_mixin.py:149} INFO - [2023-06-22T17:00:13.445+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T17:00:14.973+0200] {logging_mixin.py:149} INFO - [2023-06-22T17:00:14.973+0200] {usecase_dag.py:50} INFO - current directory /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow
[2023-06-22T17:00:15.671+0200] {logging_mixin.py:149} WARNING - 2023/06/22 17:00:15 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2023-06-22T17:00:15.673+0200] {logging_mixin.py:149} WARNING - 2023/06/22 17:00:15 INFO mlflow.store.db.utils: Updating database tables
[2023-06-22T17:00:15.678+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T17:00:15.678+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T17:00:15.699+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
[2023-06-22T17:00:15.699+0200] {logging_mixin.py:149} WARNING - INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-06-22T17:00:15.713+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): perform_etl>, training already registered for DAG: dag_with_usecase
[2023-06-22T17:00:15.713+0200] {logging_mixin.py:149} WARNING - WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): training>, perform_etl already registered for DAG: dag_with_usecase
[2023-06-22T17:00:15.718+0200] {processor.py:836} INFO - DAG(s) dict_keys(['dag_with_usecase']) retrieved from /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py
[2023-06-22T17:00:15.780+0200] {processor.py:179} INFO - Processing /Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/usecase_dag.py took 2.338 seconds
