[2023-06-22T15:50:39.299+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PythonOperator-1.task_1 manual__2023-06-22T13:50:36.210300+00:00 [queued]>
[2023-06-22T15:50:39.304+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PythonOperator-1.task_1 manual__2023-06-22T13:50:36.210300+00:00 [queued]>
[2023-06-22T15:50:39.304+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-22T15:50:39.311+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): task_1> on 2023-06-22 13:50:36.210300+00:00
[2023-06-22T15:50:39.313+0200] {standard_task_runner.py:57} INFO - Started process 86601 to run task
[2023-06-22T15:50:39.318+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'PythonOperator-1', 'task_1', 'manual__2023-06-22T13:50:36.210300+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/pythonoperator-1.py', '--cfg-path', '/var/folders/cm/7f6kgxhn6qgb2r_wq92h422h0000gn/T/tmpuch8d13d']
[2023-06-22T15:50:39.320+0200] {standard_task_runner.py:85} INFO - Job 11: Subtask task_1
[2023-06-22T15:50:39.353+0200] {task_command.py:410} INFO - Running <TaskInstance: PythonOperator-1.task_1 manual__2023-06-22T13:50:36.210300+00:00 [running]> on host saumyas-macbook-pro.local
[2023-06-22T15:50:39.392+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='spiderman' AIRFLOW_CTX_DAG_ID='PythonOperator-1' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T13:50:36.210300+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T13:50:36.210300+00:00'
[2023-06-22T15:50:39.394+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saumyagoyal/JupyterNotebook/MLCon/MLCon_23/2_airflow/dags/pythonoperator-1.py", line 12, in foo
    print|("I am fooing here..")
    ~~~~~^^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'builtin_function_or_method' and 'str'
[2023-06-22T15:50:39.398+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=PythonOperator-1, task_id=task_1, execution_date=20230622T135036, start_date=20230622T135039, end_date=20230622T135039
[2023-06-22T15:50:39.404+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task task_1 (unsupported operand type(s) for |: 'builtin_function_or_method' and 'str'; 86601)
[2023-06-22T15:50:39.417+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T15:50:39.429+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
